name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: dropdown
    id: app
    attributes:
      label: App
      options:
        - Web (app.seqrets.app)
        - Desktop (macOS)
        - Desktop (Windows)
        - Desktop (Linux)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. 1.3.8
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug clearly and concisely.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser (web app only)
      placeholder: e.g. Chrome 120, Safari 17, Firefox 121

  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Screenshots, error messages, console output, etc.
