#!/usr/bin/env node
/**
 * Reads version + codename from the root package.json and writes a typed
 * version module for the desktop app:
 *
 *   packages/desktop/src/generated/version.ts
 *
 * Exports: VERSION, CODENAME, VERSION_STRING.
 *
 * Runs before the desktop dev and build scripts. The generated file is
 * gitignored; regenerating is cheap (<10 ms).
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(join(repoRoot, 'package.json'), 'utf8'));

const VERSION = pkg.version;
const CODENAME = pkg.codename;

if (!VERSION || !CODENAME) {
  console.error('generate-version: package.json must have both `version` and `codename`');
  process.exit(1);
}

const VERSION_STRING = `v${VERSION} 🔥 ${CODENAME}`;

const moduleContent = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit.
// Source: root package.json (\`version\` + \`codename\`).

export const VERSION = ${JSON.stringify(VERSION)};
export const CODENAME = ${JSON.stringify(CODENAME)};
export const VERSION_STRING = ${JSON.stringify(VERSION_STRING)};
`;

const target = join(repoRoot, 'packages', 'desktop', 'src', 'generated', 'version.ts');
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, moduleContent);

console.log(`generate-version: wrote ${VERSION_STRING} to ${target.slice(repoRoot.length + 1)}`);
