/**
 * Generates a printable PDF from an InheritancePlan using jsPDF.
 * Designed for letter-size paper with clean typography for non-technical readers.
 */
import { jsPDF } from 'jspdf';
import type { InheritancePlan } from '@seqrets/crypto';
import { planFileLastName } from '@seqrets/crypto';
import logoPng from '@/assets/icons/logo-light-128.png';

// ── Layout constants ──────────────────────────────────────────────────
const PAGE_W = 215.9; // Letter width in mm
const PAGE_H = 279.4; // Letter height in mm
const MARGIN_L = 20;
const MARGIN_R = 20;
const MARGIN_T = 25;
const MARGIN_B = 25;
const CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R;
const FOOTER_Y = PAGE_H - 15;

// Font sizes
const TITLE_SIZE = 20;
const SECTION_SIZE = 14;
const BODY_SIZE = 10;
const SMALL_SIZE = 8;
const TABLE_SIZE = 9;

// Colors
const PRIMARY_COLOR: [number, number, number] = [35, 31, 32]; // #231f20
const MUTED_COLOR: [number, number, number] = [120, 113, 108];
const LINE_COLOR: [number, number, number] = [200, 200, 200];
const HEADER_BG: [number, number, number] = [245, 243, 240];

let currentY = MARGIN_T;
let pageNumber = 1;
let doc: jsPDF;

// ── Helpers ───────────────────────────────────────────────────────────

/**
 * Check if a table row has meaningful user-entered data. `ignoreCols` lists
 * the column indices whose content is app-prefilled (row numbers, default
 * role labels) and therefore doesn't count as data. Explicit indices — the
 * old positional `skipColumns` treated a beneficiary's NAME as a default
 * label and silently dropped name-only rows from the printed plan. It was
 * also passed as an Array.some() callback, which fed the row INDEX in as
 * the skip count.
 */
function rowHasData(cells: string[], ignoreCols: number[] = []): boolean {
  return cells.some((cell, i) => !ignoreCols.includes(i) && cell.trim().length > 0);
}

function addFooter() {
  doc.setFontSize(SMALL_SIZE);
  doc.setTextColor(...MUTED_COLOR);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by seQRets \u2014 seqrets.app', MARGIN_L, FOOTER_Y);
  doc.text(`Page ${pageNumber}`, PAGE_W - MARGIN_R, FOOTER_Y, { align: 'right' });
}

function checkPageBreak(neededHeight: number) {
  if (currentY + neededHeight > PAGE_H - MARGIN_B) {
    // addFooter() switches to the footer's small/muted style. Breaks fire
    // mid-block (inside addTextBlock/addTable loops), so restore the
    // caller's font state afterwards or every block that spans a page
    // boundary continues in 8pt gray on the new page.
    const size = doc.getFontSize();
    const font = doc.getFont();
    const color = doc.getTextColor();
    addFooter();
    doc.addPage();
    pageNumber++;
    currentY = MARGIN_T;
    doc.setFontSize(size);
    doc.setFont(font.fontName, font.fontStyle);
    doc.setTextColor(color);
  }
}

function addSectionHeader(title: string) {
  // Room for the header AND its first few lines, so a header never sits
  // alone at the foot of a page.
  checkPageBreak(36);
  currentY += 6;

  // Draw background bar
  doc.setFillColor(...HEADER_BG);
  doc.rect(MARGIN_L, currentY - 5, CONTENT_W, 9, 'F');

  doc.setFontSize(SECTION_SIZE);
  doc.setTextColor(...PRIMARY_COLOR);
  doc.setFont('helvetica', 'bold');
  doc.text(title, MARGIN_L + 3, currentY + 1);
  currentY += 10;
}

function addLabelValue(label: string, value: string) {
  if (!value) return;
  checkPageBreak(8);
  doc.setFontSize(BODY_SIZE);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PRIMARY_COLOR);
  const labelStr = `${label}: `;
  doc.text(labelStr, MARGIN_L + 2, currentY);
  // Measure width while still in bold (same font used to render the label)
  const labelWidth = doc.getTextWidth(labelStr);
  doc.setFont('helvetica', 'normal');
  const maxWidth = CONTENT_W - labelWidth - 4;
  const lines: string[] = doc.splitTextToSize(value, maxWidth);
  // Line by line, so a long value (a descriptor, a list of recovery codes)
  // continues on the next page instead of running off this one.
  lines.forEach((line, i) => {
    if (i > 0) checkPageBreak(5);
    doc.text(line, MARGIN_L + 2 + labelWidth, currentY);
    currentY += 5;
  });
}

function addTextBlock(text: string) {
  if (!text) return;
  doc.setFontSize(BODY_SIZE);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...PRIMARY_COLOR);
  const lines = doc.splitTextToSize(text, CONTENT_W - 4);
  for (const line of lines) {
    checkPageBreak(6);
    doc.text(line, MARGIN_L + 2, currentY);
    currentY += 5;
  }
}

function addTable(headers: string[], rows: string[][], colWidths: number[], ignoreCols: number[] = []) {
  // Filter out rows that have no meaningful data
  const filteredRows = rows.filter(r => rowHasData(r, ignoreCols));
  if (filteredRows.length === 0) return;

  const rowHeight = 6;
  const cellPadding = 2;

  // Header row
  checkPageBreak(rowHeight * 2);
  doc.setFillColor(...HEADER_BG);
  doc.rect(MARGIN_L, currentY - 4, CONTENT_W, rowHeight, 'F');
  doc.setFontSize(TABLE_SIZE);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PRIMARY_COLOR);

  let x = MARGIN_L + cellPadding;
  for (let i = 0; i < headers.length; i++) {
    doc.text(headers[i], x, currentY);
    x += colWidths[i];
  }
  currentY += rowHeight - 1;

  // Draw header bottom line
  doc.setDrawColor(...LINE_COLOR);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_L, currentY - 2, MARGIN_L + CONTENT_W, currentY - 2);

  // Data rows
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(TABLE_SIZE);
  const lineHeight = 4; // mm per line of text
  for (const row of filteredRows) {
    // Calculate row height based on wrapped text
    let maxLines = 1;
    const wrappedCells: string[][] = [];
    for (let i = 0; i < row.length; i++) {
      const cellWidth = colWidths[i] - cellPadding * 2;
      const wrapped = doc.splitTextToSize(row[i] || '', cellWidth);
      wrappedCells.push(wrapped);
      maxLines = Math.max(maxLines, wrapped.length);
    }
    const neededHeight = maxLines * lineHeight + 3;

    checkPageBreak(neededHeight);
    x = MARGIN_L + cellPadding;
    for (let i = 0; i < wrappedCells.length; i++) {
      // Vertically center this cell's text within the full row height
      const cellLines = wrappedCells[i].length;
      const cellTextHeight = cellLines * lineHeight;
      const offsetY = (neededHeight - cellTextHeight) / 2;
      doc.text(wrappedCells[i], x, currentY + offsetY);
      x += colWidths[i];
    }
    currentY += neededHeight;

    // Row separator
    doc.setDrawColor(...LINE_COLOR);
    doc.setLineWidth(0.1);
    doc.line(MARGIN_L, currentY - 2, MARGIN_L + CONTENT_W, currentY - 2);
  }
  currentY += 2;
}

// ── Logo embedding ────────────────────────────────────────────────────

let cachedLogoData: string | null = null;

async function loadLogoBase64(): Promise<string | null> {
  if (cachedLogoData) return cachedLogoData;
  try {
    const response = await fetch(logoPng);
    const blob = await response.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onload = () => {
        cachedLogoData = reader.result as string;
        resolve(cachedLogoData);
      };
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

// ── Main export ───────────────────────────────────────────────────────

export async function generatePlanPdf(plan: InheritancePlan): Promise<jsPDF> {
  doc = new jsPDF({ unit: 'mm', format: 'letter' });
  currentY = MARGIN_T;
  pageNumber = 1;

  // ── Logo + Title ──
  const logoData = await loadLogoBase64();
  const logoSize = 18;
  const titleText = 'seQRets Inheritance Plan';
  doc.setFontSize(TITLE_SIZE);
  doc.setFont('helvetica', 'bold');
  const titleWidth = doc.getTextWidth(titleText);

  if (logoData) {
    const totalWidth = logoSize + 3 + titleWidth;
    const startX = (PAGE_W - totalWidth) / 2;
    doc.addImage(logoData, 'PNG', startX, currentY - 6, logoSize, logoSize);
    doc.setTextColor(...PRIMARY_COLOR);
    doc.text(titleText, startX + logoSize + 3, currentY + 5);
  } else {
    doc.setTextColor(...PRIMARY_COLOR);
    doc.text(titleText, PAGE_W / 2, currentY, { align: 'center' });
  }
  currentY += 16;

  // Subtitle line
  doc.setDrawColor(...PRIMARY_COLOR);
  doc.setLineWidth(0.5);
  doc.line(MARGIN_L, currentY, PAGE_W - MARGIN_R, currentY);
  currentY += 8;

  // Plan info line
  doc.setFontSize(BODY_SIZE);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...MUTED_COLOR);
  const infoLines = [];
  if (plan.planInfo.preparedBy) infoLines.push(`Prepared by: ${plan.planInfo.preparedBy}`);
  if (plan.planInfo.planVersion) infoLines.push(`Plan v${plan.planInfo.planVersion}`);
  if (plan.planInfo.dateCreated) infoLines.push(`Created: ${plan.planInfo.dateCreated}`);
  if (plan.planInfo.lastUpdated) infoLines.push(`Last updated: ${plan.planInfo.lastUpdated}`);
  if (plan.planInfo.reviewSchedule) infoLines.push(`Review schedule: ${plan.planInfo.reviewSchedule}`);
  // With every field filled the joined line is wider than the page.
  // Wrap at the segment separators (never mid-label): greedily pack whole
  // segments into lines that fit the content width, centring each line.
  const SEP = '   |   ';
  const packedInfo: string[] = [];
  for (const segment of infoLines) {
    const tail = packedInfo[packedInfo.length - 1];
    const candidate = tail ? tail + SEP + segment : segment;
    if (tail && doc.getTextWidth(candidate) <= CONTENT_W) {
      packedInfo[packedInfo.length - 1] = candidate;
    } else {
      packedInfo.push(segment);
    }
  }
  for (const line of packedInfo) {
    doc.text(line, PAGE_W / 2, currentY, { align: 'center' });
    currentY += 5;
  }
  currentY += 5;

  // ── Confidentiality notice ──
  doc.setFontSize(SMALL_SIZE);
  doc.setFont('helvetica', 'bolditalic');
  doc.setTextColor(180, 50, 50);
  doc.text(
    'CONFIDENTIAL \u2014 This document contains sensitive recovery credentials. Store securely and destroy all copies when no longer needed.',
    PAGE_W / 2, currentY, { align: 'center', maxWidth: CONTENT_W }
  );
  currentY += 10;

  let sectionNum = 1;

  // ── Next steps for your family ── first: it is what an heir needs to
  // read before anything else in the plan.
  if (plan.nextSteps?.trim()) {
    addSectionHeader(`${sectionNum++}. Next Steps for Your Family \u2014 Read This First`);
    addTextBlock(plan.nextSteps);
    currentY += 4;
  }

  // ── Beneficiaries ──
  const beneficiaryRows = (plan.beneficiaries ?? []).map(b => [b.name, b.relationship, b.contactInfo, b.assignedAssets]);
  if (beneficiaryRows.some(r => rowHasData(r)) || plan.distributionInstructions?.trim()) {
    addSectionHeader(`${sectionNum++}. Beneficiaries`);
    addTable(
      ['Name', 'Relationship', 'Contact Info', 'Assigned Assets'],
      beneficiaryRows,
      [35, 30, 45, 65],
      [], // every column, the name included, is user-entered data
    );
    if (plan.distributionInstructions?.trim()) {
      addLabelValue('Distribution Instructions', plan.distributionInstructions);
    }
    currentY += 4;
  }

  // ── Device & Account Access ──
  const deviceRows = (plan.deviceAccounts ?? []).map(d => [d.label, d.type, d.location, d.username, d.password, d.notes]);
  if (deviceRows.some(r => rowHasData(r, [1]))) {
    addSectionHeader(`${sectionNum++}. Device & Account Access`);
    // 2FA deadlock warning. Plain text on purpose: U+26A0 (warning sign)
    // is not in the standard Helvetica encoding and forces jsPDF into a
    // UTF-16 fallback that renders as garbage glyphs.
    doc.setFontSize(SMALL_SIZE);
    doc.setFont('helvetica', 'bolditalic');
    doc.setTextColor(180, 140, 50);
    const deadlockWarning = '2FA DEADLOCK WARNING: If your password manager requires a 2FA code and your 2FA app login is inside that password manager, neither can be opened first. Make sure your 2FA app recovery credentials are listed separately below.';
    const deadlockLines = doc.splitTextToSize(deadlockWarning, CONTENT_W - 4) as string[];
    checkPageBreak(deadlockLines.length * 3.5 + 4);
    doc.text(deadlockLines, MARGIN_L + 2, currentY);
    currentY += deadlockLines.length * 3.5 + 4;
    addTable(
      ['Device', 'Type', 'Location', 'Username', 'Password', 'Notes'],
      deviceRows,
      [30, 28, 30, 28, 28, 31],
      [1], // only the Type column is prefilled; a label alone is real data
    );
  }

  // ── Digital Asset Inventory ──
  const assets = (plan.digitalAssets ?? []).filter(a => a.name || a.platform);
  if (assets.length > 0) {
    addSectionHeader(`${sectionNum++}. Digital Asset Inventory`);
    doc.setFontSize(SMALL_SIZE);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(...MUTED_COLOR);
    const custodialNote = 'Note for custodial platforms (exchanges, hosted accounts): most have a formal inheritance process requiring a death certificate. Use that legal path first \u2014 logging into a deceased person\u2019s account can violate the platform\u2019s terms or local law, and identity checks may freeze the account mid-withdrawal.';
    const custodialLines = doc.splitTextToSize(custodialNote, CONTENT_W - 4) as string[];
    checkPageBreak(custodialLines.length * 3.5 + 4);
    doc.text(custodialLines, MARGIN_L + 2, currentY);
    currentY += custodialLines.length * 3.5 + 4;
    for (const asset of assets) {
      checkPageBreak(30);
      doc.setFontSize(BODY_SIZE);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...PRIMARY_COLOR);
      const assetTitle = [asset.name, asset.type].filter(Boolean).join(' \u2014 ');
      if (assetTitle) {
        doc.text(assetTitle, MARGIN_L + 2, currentY);
        currentY += 5;
      }
      doc.setFont('helvetica', 'normal');
      addLabelValue('Platform', asset.platform);
      addLabelValue('Login Email', asset.loginEmail);
      addLabelValue('Approx. Value', asset.approxValue);
      addLabelValue('2FA Method', asset.twoFactorMethod);
      addLabelValue('Recovery Seed', asset.recoverySeed);
      addLabelValue('Wallet Kind', asset.walletKind);
      if (asset.usesPassphrase === 'yes' || asset.usesPassphrase === 'no') {
        addLabelValue('Added Passphrase ("25th word")', asset.usesPassphrase === 'yes'
          ? 'YES \u2014 the seed alone opens an EMPTY wallet; the passphrase is also required'
          : 'No \u2014 the seed phrase alone is sufficient');
      }
      addLabelValue('Passphrase', asset.passphrase ?? '');
      addLabelValue('Derivation Path / Script Type', asset.derivationPath);
      addLabelValue('Multisig Descriptor', asset.multisigDescriptor ?? '');
      addLabelValue('Other Copies of the Descriptor', asset.multisigDescriptorLocation);
      const keys = (asset.multisigKeys ?? []).filter(k => k.label || k.heldBy || k.seed || k.passphrase || k.notes);
      keys.forEach((k, i) => {
        checkPageBreak(12);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...PRIMARY_COLOR);
        doc.text(`Multisig key ${i + 1}${k.label ? ` \u2014 ${k.label}` : ''}`, MARGIN_L + 4, currentY);
        currentY += 5;
        doc.setFont('helvetica', 'normal');
        addLabelValue('Held By', k.heldBy);
        addLabelValue('Seed', k.seed);
        addLabelValue('Passphrase', k.passphrase);
        addLabelValue('Notes', k.notes);
      });
      if (asset.specialInstructions) {
        addLabelValue('Instructions', asset.specialInstructions);
      }
      currentY += 3;

      // Separator between assets
      doc.setDrawColor(...LINE_COLOR);
      doc.setLineWidth(0.1);
      doc.line(MARGIN_L + 2, currentY - 1, MARGIN_L + CONTENT_W - 2, currentY - 1);
      currentY += 2;
    }
  }

  // ── Other Secrets (v7) ──
  const otherSecrets = (plan.otherSecrets ?? []).filter(o => o.title || o.secret);
  if (otherSecrets.length > 0) {
    addSectionHeader(`${sectionNum++}. Other Secrets`);
    for (const o of otherSecrets) {
      checkPageBreak(15);
      addLabelValue('Title', o.title);
      addLabelValue('Secret', o.secret);
      addLabelValue('Notes', o.notes);
      currentY += 3;
    }
  }

  // ── Documents (v7) ── listed by name only; the files stay inside the
  // encrypted plan and are never rendered into the PDF.
  const documents = plan.documents ?? [];
  if (documents.length > 0) {
    addSectionHeader(`${sectionNum++}. Documents`);
    addTextBlock('These files are stored inside the Locker. Open the Locker in seQRets to save a copy of them.');
    for (const d of documents) {
      checkPageBreak(12);
      addLabelValue('Document', d.name === d.fileName ? d.name : `${d.name} (${d.fileName})`);
      addLabelValue('Notes', d.notes);
      currentY += 2;
    }
  }

  // ── Appendix: Recreating the Wallets ──
  // Written for an heir who has never heard the word "multisig". The plan
  // gets them to a recovered seed phrase; this section gets them from the
  // seed phrase to the actual funds — the step most inheritance documents
  // silently skip, and where most self-custody inheritance losses happen.
  // Rendered even with an empty asset inventory: the default "Next Steps for
  // Your Family" text (step 4) points heirs at this section in every plan,
  // and the guidance stands on its own.
  addSectionHeader(`${sectionNum++}. Recreating the Wallets \u2014 Read Before Moving Any Funds`);

  const sub = (title: string) => {
    checkPageBreak(10);
    doc.setFontSize(BODY_SIZE);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...PRIMARY_COLOR);
    doc.text(title, MARGIN_L + 2, currentY);
    currentY += 5;
  };

  addTextBlock(
    'A recovered seed phrase is not money you can spend yet \u2014 it is the master key to a wallet. To reach the funds, the wallet has to be recreated in wallet software using that key. Take your time: nothing about a wallet expires in a day, and the most expensive mistakes happen when people rush this step.'
  );
  currentY += 2;

  sub('The golden rule: an empty balance does NOT mean the money is gone');
  addTextBlock(
    'If you restore a seed and the wallet shows zero, the overwhelmingly likely explanation is that a detail below is missing \u2014 an added passphrase, a different derivation path, or a multisig setup. Do not panic, do not create a new wallet over it, and do not assume the funds were spent. Stop and check the asset\u2019s entry in this plan.'
  );
  currentY += 2;

  sub('If the asset says it uses an added passphrase (\u201C25th word\u201D)');
  addTextBlock(
    'The seed phrase alone will open a real \u2014 but empty \u2014 wallet. The wallet holding the funds only appears when the passphrase is entered along with the seed during restore. The passphrase is listed with the asset in this plan. Without it, no expert can reach the funds.'
  );
  currentY += 2;

  sub('For an ordinary (single-signature) wallet');
  addTextBlock(
    '(1) On a clean computer, install the wallet software named under \u201CPlatform\u201D for that asset \u2014 download it only from the official website. (2) Choose \u201CRestore\u201D or \u201CImport\u201D, never \u201CCreate new\u201D. (3) Enter the recovered seed phrase (and passphrase, if used). (4) If the balance looks wrong, check the derivation path / script type listed with the asset \u2014 wallet software sometimes needs to be told which \u201Caccount type\u201D to look for.'
  );
  currentY += 2;

  sub('If the asset is marked multisig \u2014 do not skip this');
  addTextBlock(
    'A multisig wallet is controlled by SEVERAL keys \u2014 for example \u201C2-of-3\u201D means any two of three keys must sign. Restoring it needs two things: enough of the seed phrases, AND the wallet\u2019s configuration file (called a \u201Cdescriptor\u201D or \u201Cwallet file\u201D), which lists all the keys that belong together. The descriptor is listed with the asset in this plan. With it, recovery is: open the wallet software, import the descriptor, then add the seeds \u2014 the software does the rest. Without it, reconstruction may be impossible even for a professional. If you cannot find the descriptor, stop and call the Technical Contact listed under Professional Contacts before doing anything else.'
  );
  currentY += 2;

  sub('For accounts on an exchange or other custodial platform');
  addTextBlock(
    'There is no wallet to recreate \u2014 the platform holds the funds. Contact their support about their inheritance / estate process (they will ask for a death certificate and proof of authority). This is the legal and safest path.'
  );
  currentY += 2;

  sub('When in doubt');
  addTextBlock(
    'The Technical Contact under Professional Contacts was chosen to help with exactly this section. A one-hour call before touching anything is worth more than any guide. Never type a seed phrase into a website, never share it with \u201Csupport staff\u201D who contact you first, and be aware that scammers watch obituaries.'
  );
  currentY += 4;

  // ── Professional Contacts ──
  const contactRows = (plan.professionalContacts ?? []).map(c => [c.role, c.name, c.phone, c.email]);
  if (contactRows.some(r => rowHasData(r, [0]))) {
    addSectionHeader(`${sectionNum++}. Professional Contacts`);
    addTable(
      ['Role', 'Name', 'Phone', 'Email'],
      contactRows,
      [40, 45, 40, 50],
      [0], // the default role labels are prefilled
    );
  }

  // ── Emergency Access ──
  const ea = plan.emergencyAccess;
  if (ea && (ea.emergencyContact || ea.triggerConditions || ea.accessProcedure || ea.immediateActions || ea.scopeLimitations)) {
    addSectionHeader(`${sectionNum++}. Emergency Access`);
    addLabelValue('Emergency Contact', ea.emergencyContact);
    if (ea.triggerConditions) {
      checkPageBreak(10);
      doc.setFontSize(BODY_SIZE);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...PRIMARY_COLOR);
      doc.text('Trigger Conditions:', MARGIN_L + 2, currentY);
      currentY += 5;
      addTextBlock(ea.triggerConditions);
    }
    if (ea.accessProcedure) {
      checkPageBreak(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Access Procedure:', MARGIN_L + 2, currentY);
      currentY += 5;
      addTextBlock(ea.accessProcedure);
    }
    if (ea.immediateActions) {
      checkPageBreak(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Immediate Actions:', MARGIN_L + 2, currentY);
      currentY += 5;
      addTextBlock(ea.immediateActions);
    }
    if (ea.scopeLimitations) {
      checkPageBreak(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Scope Limitations:', MARGIN_L + 2, currentY);
      currentY += 5;
      addTextBlock(ea.scopeLimitations);
    }
    currentY += 4;
  }

  // ── Personal Message ──
  if (plan.personalMessage?.trim()) {
    addSectionHeader(`${sectionNum++}. Personal Message to Your Heirs`);
    addTextBlock(plan.personalMessage);
    currentY += 4;
  }

  // Add footer to the last page
  addFooter();

  return doc;
}

/**
 * Derive a PDF filename from the plan's "Prepared by" field.
 * E.g., "John Smith" → "Smith-Inheritance-Plan.pdf"
 */
export function getPlanPdfFilename(plan: InheritancePlan): string {
  const lastName = planFileLastName(plan.planInfo.preparedBy);
  return lastName ? `${lastName}-Inheritance-Plan.pdf` : 'seqrets-inheritance-plan.pdf';
}
