/**
 * Generates a printable PDF from an InheritancePlan using jsPDF.
 * Designed for letter-size paper with clean typography for non-technical readers.
 */
import { jsPDF } from 'jspdf';
import type { InheritancePlan } from './inheritance-plan-types';
import logoPng from '@/assets/icons/logo-light-128.png';

// ── Layout constants ──────────────────────────────────────────────────
const PAGE_W = 215.9; // Letter width in mm
const PAGE_H = 279.4; // Letter height in mm
const MARGIN_L = 20;
const MARGIN_R = 20;
const MARGIN_T = 25;
const MARGIN_B = 25;
const CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R;
const FOOTER_Y = PAGE_H - 15;

// Font sizes
const TITLE_SIZE = 20;
const SECTION_SIZE = 14;
const BODY_SIZE = 10;
const SMALL_SIZE = 8;
const TABLE_SIZE = 9;

// Colors
const PRIMARY_COLOR: [number, number, number] = [35, 31, 32]; // #231f20
const MUTED_COLOR: [number, number, number] = [120, 113, 108];
const LINE_COLOR: [number, number, number] = [200, 200, 200];
const HEADER_BG: [number, number, number] = [245, 243, 240];

let currentY = MARGIN_T;
let pageNumber = 1;
let doc: jsPDF;

// ── Helpers ───────────────────────────────────────────────────────────

/** Check if a table row has meaningful user-entered data beyond default labels. */
function rowHasData(cells: string[], skipColumns = 1): boolean {
  return cells.some((cell, i) => i >= skipColumns && cell.trim().length > 0);
}

function addFooter() {
  doc.setFontSize(SMALL_SIZE);
  doc.setTextColor(...MUTED_COLOR);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by seQRets \u2014 seqrets.app', MARGIN_L, FOOTER_Y);
  doc.text(`Page ${pageNumber}`, PAGE_W - MARGIN_R, FOOTER_Y, { align: 'right' });
}

function checkPageBreak(neededHeight: number) {
  if (currentY + neededHeight > PAGE_H - MARGIN_B) {
    addFooter();
    doc.addPage();
    pageNumber++;
    currentY = MARGIN_T;
  }
}

function addSectionHeader(title: string) {
  checkPageBreak(16);
  currentY += 6;

  // Draw background bar
  doc.setFillColor(...HEADER_BG);
  doc.rect(MARGIN_L, currentY - 5, CONTENT_W, 9, 'F');

  doc.setFontSize(SECTION_SIZE);
  doc.setTextColor(...PRIMARY_COLOR);
  doc.setFont('helvetica', 'bold');
  doc.text(title, MARGIN_L + 3, currentY + 1);
  currentY += 10;
}

function addLabelValue(label: string, value: string) {
  if (!value) return;
  checkPageBreak(8);
  doc.setFontSize(BODY_SIZE);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PRIMARY_COLOR);
  const labelStr = `${label}: `;
  doc.text(labelStr, MARGIN_L + 2, currentY);
  // Measure width while still in bold (same font used to render the label)
  const labelWidth = doc.getTextWidth(labelStr);
  doc.setFont('helvetica', 'normal');
  const maxWidth = CONTENT_W - labelWidth - 4;
  const lines = doc.splitTextToSize(value, maxWidth);
  doc.text(lines, MARGIN_L + 2 + labelWidth, currentY);
  currentY += lines.length * 5;
}

function addTextBlock(text: string) {
  if (!text) return;
  doc.setFontSize(BODY_SIZE);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...PRIMARY_COLOR);
  const lines = doc.splitTextToSize(text, CONTENT_W - 4);
  for (const line of lines) {
    checkPageBreak(6);
    doc.text(line, MARGIN_L + 2, currentY);
    currentY += 5;
  }
}

function addTable(headers: string[], rows: string[][], colWidths: number[], skipColumns = 1) {
  // Filter out rows that have no meaningful data
  const filteredRows = rows.filter(r => rowHasData(r, skipColumns));
  if (filteredRows.length === 0) return;

  const rowHeight = 6;
  const cellPadding = 2;

  // Header row
  checkPageBreak(rowHeight * 2);
  doc.setFillColor(...HEADER_BG);
  doc.rect(MARGIN_L, currentY - 4, CONTENT_W, rowHeight, 'F');
  doc.setFontSize(TABLE_SIZE);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...PRIMARY_COLOR);

  let x = MARGIN_L + cellPadding;
  for (let i = 0; i < headers.length; i++) {
    doc.text(headers[i], x, currentY);
    x += colWidths[i];
  }
  currentY += rowHeight - 1;

  // Draw header bottom line
  doc.setDrawColor(...LINE_COLOR);
  doc.setLineWidth(0.3);
  doc.line(MARGIN_L, currentY - 2, MARGIN_L + CONTENT_W, currentY - 2);

  // Data rows
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(TABLE_SIZE);
  const lineHeight = 4; // mm per line of text
  for (const row of filteredRows) {
    // Calculate row height based on wrapped text
    let maxLines = 1;
    const wrappedCells: string[][] = [];
    for (let i = 0; i < row.length; i++) {
      const cellWidth = colWidths[i] - cellPadding * 2;
      const wrapped = doc.splitTextToSize(row[i] || '', cellWidth);
      wrappedCells.push(wrapped);
      maxLines = Math.max(maxLines, wrapped.length);
    }
    const neededHeight = maxLines * lineHeight + 3;

    checkPageBreak(neededHeight);
    x = MARGIN_L + cellPadding;
    for (let i = 0; i < wrappedCells.length; i++) {
      // Vertically center this cell's text within the full row height
      const cellLines = wrappedCells[i].length;
      const cellTextHeight = cellLines * lineHeight;
      const offsetY = (neededHeight - cellTextHeight) / 2;
      doc.text(wrappedCells[i], x, currentY + offsetY);
      x += colWidths[i];
    }
    currentY += neededHeight;

    // Row separator
    doc.setDrawColor(...LINE_COLOR);
    doc.setLineWidth(0.1);
    doc.line(MARGIN_L, currentY - 2, MARGIN_L + CONTENT_W, currentY - 2);
  }
  currentY += 2;
}

// ── Logo embedding ────────────────────────────────────────────────────

let cachedLogoData: string | null = null;

async function loadLogoBase64(): Promise<string | null> {
  if (cachedLogoData) return cachedLogoData;
  try {
    const response = await fetch(logoPng);
    const blob = await response.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onload = () => {
        cachedLogoData = reader.result as string;
        resolve(cachedLogoData);
      };
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

// ── Main export ───────────────────────────────────────────────────────

export async function generatePlanPdf(plan: InheritancePlan): Promise<jsPDF> {
  doc = new jsPDF({ unit: 'mm', format: 'letter' });
  currentY = MARGIN_T;
  pageNumber = 1;

  // ── Logo + Title ──
  const logoData = await loadLogoBase64();
  const logoSize = 18;
  const titleText = 'seQRets Inheritance Plan';
  doc.setFontSize(TITLE_SIZE);
  doc.setFont('helvetica', 'bold');
  const titleWidth = doc.getTextWidth(titleText);

  if (logoData) {
    const totalWidth = logoSize + 3 + titleWidth;
    const startX = (PAGE_W - totalWidth) / 2;
    doc.addImage(logoData, 'PNG', startX, currentY - 6, logoSize, logoSize);
    doc.setTextColor(...PRIMARY_COLOR);
    doc.text(titleText, startX + logoSize + 3, currentY + 5);
  } else {
    doc.setTextColor(...PRIMARY_COLOR);
    doc.text(titleText, PAGE_W / 2, currentY, { align: 'center' });
  }
  currentY += 16;

  // Subtitle line
  doc.setDrawColor(...PRIMARY_COLOR);
  doc.setLineWidth(0.5);
  doc.line(MARGIN_L, currentY, PAGE_W - MARGIN_R, currentY);
  currentY += 8;

  // Plan info
  doc.setFontSize(BODY_SIZE);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...MUTED_COLOR);
  const infoLines = [];
  if (plan.planInfo.preparedBy) infoLines.push(`Prepared by: ${plan.planInfo.preparedBy}`);
  if (plan.planInfo.dateCreated) infoLines.push(`Created: ${plan.planInfo.dateCreated}`);
  if (plan.planInfo.lastUpdated) infoLines.push(`Last updated: ${plan.planInfo.lastUpdated}`);
  if (plan.planInfo.reviewSchedule) infoLines.push(`Review schedule: ${plan.planInfo.reviewSchedule}`);
  doc.text(infoLines.join('   |   '), PAGE_W / 2, currentY, { align: 'center' });
  currentY += 10;

  // ── Confidentiality notice ──
  doc.setFontSize(SMALL_SIZE);
  doc.setFont('helvetica', 'bolditalic');
  doc.setTextColor(180, 50, 50);
  doc.text(
    'CONFIDENTIAL \u2014 This document contains sensitive recovery credentials. Store securely and destroy all copies when no longer needed.',
    PAGE_W / 2, currentY, { align: 'center', maxWidth: CONTENT_W }
  );
  currentY += 10;

  // ── Section 1: Recovery Credentials ──
  const creds = plan.recoveryCredentials;
  if (creds.password || creds.keyfilePrimaryLocation || creds.keyfileBackupLocation) {
    addSectionHeader('1. Recovery Credentials');
    addLabelValue('Password', creds.password);
    addLabelValue('Keyfile Primary Location', creds.keyfilePrimaryLocation);
    addLabelValue('Keyfile Backup Location', creds.keyfileBackupLocation);
    currentY += 4;
  }

  // ── Section 2: Device & Account Access ──
  const deviceRows = (plan.deviceAccounts ?? []).map(d => [d.label, d.type, d.location, d.username, d.password, d.notes]);
  if (deviceRows.some(r => rowHasData(r, 2))) {
    addSectionHeader('2. Device & Account Access');
    // 2FA deadlock warning
    doc.setFontSize(SMALL_SIZE);
    doc.setFont('helvetica', 'bolditalic');
    doc.setTextColor(180, 140, 50);
    checkPageBreak(10);
    doc.text(
      '\u26A0 2FA DEADLOCK WARNING: If your password manager requires a 2FA code and your 2FA app login is inside that password manager, neither can be opened first. Make sure your 2FA app recovery credentials are listed separately below.',
      MARGIN_L + 2, currentY, { maxWidth: CONTENT_W - 4 }
    );
    currentY += 12;
    addTable(
      ['Device', 'Type', 'Location', 'Username', 'Password', 'Notes'],
      deviceRows,
      [30, 28, 30, 28, 28, 31],
      2
    );
  }

  // ── Section 3: Qard Locations ──
  const qards = plan.qardConfig;
  const qardRows = (qards.locations ?? []).map(q => [String(q.qardNumber), q.location, q.heldBy, q.accessNotes]);
  if (qardRows.some(rowHasData)) {
    addSectionHeader('3. Qard Locations');
    if (qards.configuration || qards.label) {
      doc.setFontSize(BODY_SIZE);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...PRIMARY_COLOR);
      const configLine = [
        qards.configuration && `Configuration: ${qards.configuration}`,
        qards.label && `Label: ${qards.label}`,
      ].filter(Boolean).join('   |   ');
      doc.text(configLine, MARGIN_L + 2, currentY);
      currentY += 7;
    }
    addTable(
      ['#', 'Location', 'Held By', 'Access Notes'],
      qardRows,
      [10, 55, 45, 65]
    );
  }

  // ── Section 4: Digital Asset Inventory ──
  const assets = (plan.digitalAssets ?? []).filter(a => a.name || a.platform);
  if (assets.length > 0) {
    addSectionHeader('4. Digital Asset Inventory');
    for (const asset of assets) {
      checkPageBreak(30);
      doc.setFontSize(BODY_SIZE);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...PRIMARY_COLOR);
      const assetTitle = [asset.name, asset.type].filter(Boolean).join(' \u2014 ');
      if (assetTitle) {
        doc.text(assetTitle, MARGIN_L + 2, currentY);
        currentY += 5;
      }
      doc.setFont('helvetica', 'normal');
      addLabelValue('Platform', asset.platform);
      addLabelValue('Login Email', asset.loginEmail);
      addLabelValue('Approx. Value', asset.approxValue);
      addLabelValue('2FA Method', asset.twoFactorMethod);
      addLabelValue('Recovery Seed', asset.recoverySeed);
      if (asset.specialInstructions) {
        addLabelValue('Instructions', asset.specialInstructions);
      }
      currentY += 3;

      // Separator between assets
      doc.setDrawColor(...LINE_COLOR);
      doc.setLineWidth(0.1);
      doc.line(MARGIN_L + 2, currentY - 1, MARGIN_L + CONTENT_W - 2, currentY - 1);
      currentY += 2;
    }
  }

  // ── Section 5: How to Restore Your Secret ──
  if (plan.howToRestore) {
    addSectionHeader('5. How to Restore Your Secret');
    addTextBlock(plan.howToRestore);
    currentY += 4;
  }

  // ── Section 6: Professional Contacts ──
  const contactRows = (plan.professionalContacts ?? []).map(c => [c.role, c.name, c.phone, c.email]);
  if (contactRows.some(rowHasData)) {
    addSectionHeader('6. Professional Contacts');
    addTable(
      ['Role', 'Name', 'Phone', 'Email'],
      contactRows,
      [40, 45, 40, 50]
    );
  }

  // ── Section 7: Personal Message ──
  if (plan.personalMessage?.trim()) {
    addSectionHeader('7. Personal Message to Your Heirs');
    addTextBlock(plan.personalMessage);
    currentY += 4;
  }

  // Add footer to the last page
  addFooter();

  return doc;
}

/**
 * Derive a PDF filename from the plan's "Prepared by" field.
 * E.g., "John Smith" → "Smith-Inheritance-Plan.pdf"
 */
export function getPlanPdfFilename(plan: InheritancePlan): string {
  const name = plan.planInfo.preparedBy?.trim();
  if (!name) return 'seqrets-inheritance-plan.pdf';
  const lastName = name.split(/\s+/).pop() || name;
  return `${lastName}-Inheritance-Plan.pdf`;
}
